"""Service layer facades for Alibi.

All consumers (CLI, API, MCP, Telegram, file watcher) should call
these functions instead of reaching into pipeline or store modules
directly.
"""

from alibi.services.auth import (
    add_contact,
    create_api_key,
    create_user,
    find_user_by_contact,
    find_user_by_telegram,
    get_display_name,
    get_user,
    link_telegram,
    list_api_keys,
    list_contacts,
    list_users,
    remove_contact,
    remove_contact_by_value,
    revoke_api_key,
    update_user,
    validate_api_key,
)
from alibi.services.annotation import (
    annotate,
    delete_annotation,
    get_annotations,
    update_annotation,
)
from alibi.services.analytics import (
    analyze_spending_patterns,
    cloud_quality_report,
    compare_periods,
    correction_confusion_matrix,
    detect_anomalies,
    detect_subscriptions,
    get_refinement_suggestions,
    get_upcoming_subscriptions,
    location_spending,
    monthly_report,
    nearby_vendors,
    spending_analysis,
    spending_by_month,
    spending_by_vendor,
    spending_summary,
    vendor_branches,
    vendor_cloud_accuracy,
    vendor_report,
    verify_extractions,
)
from alibi.services.correction import (
    cleanup_orphaned_annotations,
    correct_vendor,
    delete_fact_item,
    get_fact_location,
    get_recent_vendor_locations,
    mark_disputed,
    move_bundle,
    recollapse_cloud,
    reconcile_forming_clouds,
    set_fact_location,
    update_fact,
    update_fact_item,
)
from alibi.services.identity import (
    get_identity,
    list_identities,
    merge_vendors,
    resolve_vendor,
)
from alibi.services.ingestion import (
    check_yaml_changed,
    persist_upload,
    persist_upload_group,
    process_batch,
    process_bytes,
    process_document_group,
    process_file,
    reingest_from_yaml,
    scan_yaml_corrections,
)
from alibi.services.items import (
    create_item,
    delete_item,
    get_item,
    get_item_documents,
    get_item_facts,
    list_items,
    update_item,
)
from alibi.services.enrichment_review import (
    confirm_enrichment,
    find_product_matches,
    get_enrichment_trends,
    get_review_queue,
    get_review_stats,
    get_vendor_coverage,
    reject_enrichment,
)
from alibi.services.export_analytics import (
    build_export_payload,
    push_to_analytics_stack,
)
from alibi.services.predictions import (
    classify_category,
    classify_uncategorized,
    drop_model,
    get_model_status,
    get_spending_forecast,
    list_models,
    train_category_classifier,
    train_spending_forecast,
)
from alibi.services.correction_log import (
    get_vendor_correction_rate,
    get_vendor_corrections,
    list_corrections,
)
from alibi.services.maintenance import (
    cleanup_identities,
    fix_data_quality,
    recalculate_templates,
    run_maintenance,
)
from alibi.services.query import (
    category_summary,
    delete_document,
    delete_fact,
    get_document,
    get_document_line_items,
    get_fact,
    get_fact_item,
    inspect_fact,
    list_documents,
    list_fact_items,
    list_fact_items_with_fact,
    list_facts,
    list_unassigned,
    search_facts,
)

__all__ = [
    # ingestion
    "persist_upload",
    "persist_upload_group",
    "process_file",
    "process_batch",
    "process_document_group",
    "process_bytes",
    "reingest_from_yaml",
    "check_yaml_changed",
    "scan_yaml_corrections",
    # items
    "list_items",
    "get_item",
    "get_item_documents",
    "get_item_facts",
    "create_item",
    "update_item",
    "delete_item",
    # query
    "get_fact",
    "inspect_fact",
    "list_facts",
    "search_facts",
    "list_unassigned",
    "get_document",
    "get_document_line_items",
    "list_documents",
    "list_fact_items",
    "list_fact_items_with_fact",
    "get_fact_item",
    "category_summary",
    "delete_document",
    "delete_fact",
    # correction
    "delete_fact_item",
    "move_bundle",
    "recollapse_cloud",
    "reconcile_forming_clouds",
    "mark_disputed",
    "update_fact",
    "update_fact_item",
    "correct_vendor",
    "cleanup_orphaned_annotations",
    "set_fact_location",
    "get_fact_location",
    "get_recent_vendor_locations",
    # annotation
    "annotate",
    "get_annotations",
    "update_annotation",
    "delete_annotation",
    # identity
    "resolve_vendor",
    "list_identities",
    "get_identity",
    "merge_vendors",
    # enrichment review
    "get_review_queue",
    "confirm_enrichment",
    "reject_enrichment",
    "get_review_stats",
    "get_enrichment_trends",
    "get_vendor_coverage",
    "find_product_matches",
    # analytics export
    "build_export_payload",
    "push_to_analytics_stack",
    # auth
    "create_user",
    "update_user",
    "get_user",
    "get_display_name",
    "list_users",
    "add_contact",
    "remove_contact",
    "remove_contact_by_value",
    "list_contacts",
    "find_user_by_contact",
    "find_user_by_telegram",
    "link_telegram",
    "create_api_key",
    "validate_api_key",
    "list_api_keys",
    "revoke_api_key",
    # predictions
    "train_spending_forecast",
    "train_category_classifier",
    "get_spending_forecast",
    "classify_category",
    "classify_uncategorized",
    "list_models",
    "get_model_status",
    "drop_model",
    # analytics
    "spending_summary",
    "spending_by_vendor",
    "spending_by_month",
    "spending_analysis",
    "monthly_report",
    "detect_subscriptions",
    "get_upcoming_subscriptions",
    "detect_anomalies",
    "analyze_spending_patterns",
    "compare_periods",
    "vendor_report",
    "verify_extractions",
    "correction_confusion_matrix",
    "get_refinement_suggestions",
    "location_spending",
    "vendor_branches",
    "nearby_vendors",
    "cloud_quality_report",
    "vendor_cloud_accuracy",
    # correction log
    "list_corrections",
    "get_vendor_correction_rate",
    "get_vendor_corrections",
    # maintenance
    "run_maintenance",
    "recalculate_templates",
    "cleanup_identities",
]
